# Generated by Django 4.1.4 on 2022-12-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=225)),
                ('option1', models.CharField(max_length=225)),
                ('option2', models.CharField(max_length=225)),
                ('option3', models.CharField(max_length=225, null=True)),
                ('option4', models.CharField(max_length=225, null=True)),
                ('answer', models.CharField(max_length=225)),
                ('correct_answer', models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='list_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='genre',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=255),
        ),
    ]
